[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "the-yard"
authors = [{name = "Jeremy", email = "jeremy@yardpodcast.cc"}]
dynamic = ["version", "description"]
